# Setup
title:        Kanziw's Blog
tagline:      잡다한 블로그
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       kanziw
  url:        https://kanziw.github.io

disqus: kanziw

# Tag
collections:
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
